baseURL: https://geedea.pro/
timeZone: Asia/Shanghai
hasCJKLanguage: true
defaultContentLanguage: zh
defaultContentLanguageInSubdir: true

markup:
  goldmark:
    renderer:
      unsafe: true
    extensions:
      extras:
        mark:
          enable: true
  highlight:
    guessSyntax: true
    noClasses: true
    style: catppuccin-macchiato
    tabWidth: 2

services:
  rss:
    limit: 10
outputs:
  home:
    - HTML
    - calheatmap
    - RSS
outputFormats:
  calheatmap:
    mediaType: application/json
    baseName: cal-heatmap
    isPlainText: true
    permalinkable: true
