zh:
  contentDir: content
  defaultContentLanguageInSubdir: false
  disabled: false
  languageCode: zh-CN
  languageDirection: ltr
  languageName: 简体中文
  params:
    headTitle: CDown's {Space}
    nav:
      - name: 发表
        link: /posts/
        target: _self
      - name: 砖块
        link: /cards/
        target: _self
      - name: 思绪
        link: /fictions/
        target: _self
      - name: 自述
        link: /about/
        target: _self
    series:
      - name: 情报
        link: /categories/情报/
        cover: https://image.guhub.cn/uPic/2025/01/%E7%A8%BB%E8%8D%89%E4%BA%BA%E5%91%A8%E5%88%8A.jpeg
        description: 关注的信息整合
  title: CDown's Space
  weight: 1
en:
  contentDir: content/en
  disabled: false
  languageCode: en-US
  languageDirection: ltr
  languageName: English
  params:
    headTitle: CDown's {Space}
    nav:
      - name: /about
        link: /en/about/
        target: _self
      # - name: /categories
      #   link: /en/categories/
      #   target: _self
      - name: /blogroll
        link: /en/blogroll/
        target: _self
  title: CDown's Space
  weight: 2
